# Generated by Django 4.1.3 on 2022-11-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='Data published')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katalog', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('release', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storage.release')),
            ],
        ),
    ]
